Revert "fix: #41981, correction of "TypeError: idCalendars.forEach is not a function" which prevents displaying the calendar."
This reverts commit 9a4479947c529d33b3c10600652d30976eb05b94.